server:
  port: 8302

spring:
  application:
    name: redis

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        #  获取连接时的最大等待毫秒数,小于零:阻塞不确定的时间,默认-1
        max-wait: -1
        # 最大空闲连接数
        max-idle: 8
        # 最小空闲连接数
        min-idle: 0

