server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
spring:
  application:
    name: eureka-server
eureka:
  instance: #定义Eureka实例
    hostname: eureka-server #Eureka实例所在的主机名
    appname: eureka
    prefer-ip-address: true #访问路径变为IP地址
    health-check-url-path: /actuator/health
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #    lease-expiration-duration-in-seconds: 5 #设置心跳的周期间隔(默认90s)[如果5s没响应默认服务宕机]
  #    lease-renewal-interval-in-seconds: 2  #设置心跳时间间隔(默认30s)
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false #关闭保护模式
    peer-node-read-timeout-ms: 10000
  #    eviction-interval-timer-in-ms: 6000 #设置清理的间隔时间(默认6000ms)
  client:
    register-with-eureka: false #表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    fetch-registry: false #表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据,所以置为false
    service-url:
      defaultZone: http://localhost:8761/eureka/ #设置Eureka的地址,逗号隔开配置多个注册中心
