server:
  port: 8000

spring:
  application:
    name: zuul-server

info:
  description: 网关

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #向注册中心注册IP
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

zuul:
  retryable: true
  routes:
    security-oauth:
      path: /security-service/**
    user-manager:
      path: /user-manager-service/**
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  sensitive-headers:
